-- DBSpeed : colonne « sources » des lieux + les vrais lieux de Slovaquie (4 pistes de BMX race, 64 pump tracks)
-- Déjà appliqué sur le projet Supabase « DBSpeed » le 01/10/2026 (ne pas relancer).
-- Les lignes sont fabriquées par outils/lieux-slovaquie.py (recherche du 01/10/2026, chaque lieu a ses sources).

alter table public.lieux add column sources jsonb not null default '[]'::jsonb,
  add constraint lieu_sources_liste check (jsonb_typeof(sources) = 'array' and jsonb_array_length(sources) <= 10);
comment on column public.lieux.sources is 'Liens qui prouvent les infos : [{"nom": "...", "url": "https://..."}]';
grant insert (sources) on public.lieux to authenticated;
grant update (sources) on public.lieux to authenticated;

insert into public.lieux (id, genre, nom, latitude, longitude, adresse, horaires, acces, trace, club, club_site, sources) values
('way-23126138', 'bmx', 'BMX dráha BMX klub Rača', 48.20316625622933, 17.14658026732454, 'Hečkova 3, 831 51 Bratislava-Rača', 'Pendant les travaux de la LBG aréna autour de la piste : entraînement seulement après accord avec le club.', 'club', '417 m, 4 virages à 180° (le premier à gauche) et 14 sauts. Grille de départ pneumatique avec voicebox. Lignes droites et virages modernisés en 2025. Plus de 160 manches de la Coupe de Slovaquie et 26 championnats de Slovaquie courus ici.', 'BMX klub Rača (depuis 1985)', 'https://bmx-raca.sk', '[{"nom": "BMX klub Rača – la piste", "url": "https://bmx-raca.sk/new/page/track/"}, {"nom": "BMX klub Rača – le club", "url": "https://bmx-raca.sk/new/page/club/"}, {"nom": "OpenStreetMap (oma.sk)", "url": "https://poi.oma.sk/w23126138"}, {"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/bmx-ra-a/"}]'::jsonb),
('way-914145616', 'bmx', 'BMX dráha Furča (bikros Košice)', 48.73928699275788, 21.279390049556735, 'Sídlisko Dargovských hrdinov (Furča), entre Lidické námestie et la rue Benadova, Košice', null, 'public', '390 m, 7 virages et 11 groupes de bosses. Butte de départ refaite en 2023 avec une grille de départ ProStar certifiée. Surface recouverte de dolomite. Accueille des manches de la Coupe de Slovaquie et des championnats de Slovaquie.', 'BMX Klub Košický šarkaň', 'https://www.kosickysarkan.sk', '[{"nom": "BMX Klub Košický šarkaň", "url": "https://www.kosickysarkan.sk/"}, {"nom": "OpenStreetMap (oma.sk)", "url": "https://poi.oma.sk/w914145616"}, {"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/bikros-fur-a/"}, {"nom": "invisiblemag – rouler à Košice", "url": "https://www.invisiblemag.sk/en/infinite-ways-how-to-bike-in-kosice/"}]'::jsonb),
('way-488771732', 'bmx', 'BMX dráha BMX TEAM LIPTOV', 49.070848167630764, 19.627670087876776, 'Vrbica, Liptovský Mikuláš (à côté de la piste cyclable le long du Váh)', null, null, 'Une des plus grandes pistes de bikros de Slovaquie. Dans le même parc : un pump track en enrobé de 280 m, des dirts et un pump track d’entraînement.', 'BMX TEAM LIPTOV (depuis 1987)', 'http://www.bmx-liptov.sk', '[{"nom": "OpenStreetMap (oma.sk)", "url": "https://poi.oma.sk/w488771732"}, {"nom": "visitliptov – Pumptrack & BMX park", "url": "https://www.visitliptov.sk/en/interests/pumptrack-bmx-park/"}, {"nom": "visitliptov – Coupe de Slovaquie 2024", "url": "https://www.visitliptov.sk/podujatie/slovensky-pohar-bmx-racing-2024/"}]'::jsonb),
('way-78169544', 'bmx', 'BMX dráha Dunajská Lužná (Bike centrum HENKY Riders)', 48.077380745234684, 17.256076635844458, 'Rekreačná ulica, Jánošíková, Dunajská Lužná', 'Entraînements du club (piste fermée au public) : lundi et mercredi, 16 h 30 – 19 h.', null, 'Surface compactée. Sur le site : pump tracks, dirt park, trial park et école de vélo (dès 3 ans).', 'HENKY Riders', 'https://henky-riders.webnode.sk', '[{"nom": "HENKY Riders – Bike centrum", "url": "https://henky-riders.webnode.sk/bike-centrum-henky-riders2/"}, {"nom": "OpenStreetMap (oma.sk)", "url": "https://poi.oma.sk/w78169544"}, {"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/bmx-draha-dunajska-lu-na/"}]'::jsonb),
('dbs-sk-pumppark-petrzalka', 'pump', 'PumpPark Petržalka', 48.121438, 17.124741, 'Haanova, Bratislava-Petržalka', null, 'public', 'Environ 600 m de lignes en enrobé, dont la « Bambi line » pour les petits. Ouvert en 2021 sur l’ancienne piste de bikros. Éclairé. Casque obligatoire.', 'OZ Pedál', 'https://pumppark.sk', '[{"nom": "pumppark.sk", "url": "https://pumppark.sk/"}, {"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/pumppark-petr-alka/"}, {"nom": "startitup.sk – ouverture", "url": "https://www.startitup.sk/v-bratislave-otvorili-unikat-aky-nenajdes-nikde-inde-v-strednej-europe-potesi-najma-sportovcov/"}]'::jsonb),
('way-740310145', 'pump', 'Pedal pumptrack Vrakuňa', 48.147903, 17.203995, 'Lesopark Vrakuňa (Brezová / Malodunajská), Bratislava', null, 'public', '75 m, en enrobé depuis 2020 (en terre avant). Pas d’éclairage.', 'OZ Pedál', null, '[{"nom": "OpenStreetMap (oma.sk)", "url": "https://poi.oma.sk/w740310145"}, {"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/pedal-pumptrack-vraku-a/"}, {"nom": "medvedkudajlabku.sk – pump tracks de Bratislava", "url": "https://medvedkudajlabku.sk/pumptrack/"}]'::jsonb),
('dbs-sk-podunajske-biskupice', 'pump', 'Pump track Podunajské Biskupice', 48.13508, 17.212193, 'Latorická, Bratislava-Podunajské Biskupice', null, 'public', 'En enrobé, ouvert en 2021. Pas d’éclairage.', null, null, '[{"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/pump-track-podunajske-biskupice/"}, {"nom": "medvedkudajlabku.sk – pump tracks de Bratislava", "url": "https://medvedkudajlabku.sk/pumptrack/"}]'::jsonb),
('dbs-sk-ruzinov', 'pump', 'Pump track Ružinov', 48.155979, 17.154849, 'Bratislava-Ružinov', null, null, null, null, null, '[{"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/pump-track-ruzinov/"}]'::jsonb),
('dbs-sk-dubravka', 'pump', 'Pump track Dúbravka', 48.181964, 17.036317, 'Talichova, Bratislava-Dúbravka', null, null, 'Petit pump track en enrobé (40 à 50 m d’après le projet).', null, null, '[{"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/pump-track-dubravka/"}, {"nom": "Dúbravka – projet", "url": "https://www.dubravka.sk/files/documents/novinky/pumptrack-talichova.pdf"}]'::jsonb),
('dbs-sk-zahorska-bystrica', 'pump', 'Pump track Záhorská Bystrica', 48.235644, 17.039443, 'Bratislava-Záhorská Bystrica', null, null, 'En enrobé, ouvert vers 2022.', null, null, '[{"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/pump-track-zahorska-bystrica/"}]'::jsonb),
('dbs-sk-parkitect-raca', 'pump', 'Pump track modulaire Parkitect (Rača)', 48.201144, 17.164544, 'Sklabinská, Bratislava-Rača', null, null, 'Pump track modulaire (éléments posés).', null, null, '[{"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/parkitect-modular-pumptrack-bowtie-ra-a/"}]'::jsonb),
('way-1186014862', 'pump', 'Pumptrack Zochova chata – Piesok', 48.382043, 17.275872, 'Modra-Piesok, près de l’hôtel Zochova chata', 'Été : 8 h – 20 h
Hiver : 8 h – 18 h', null, 'En enrobé, ouvert en 2017, terrain clôturé. Pas d’éclairage.', null, null, '[{"nom": "OpenStreetMap (oma.sk)", "url": "https://poi.oma.sk/w1186014862"}, {"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/pumptrack-modrapiesok/"}, {"nom": "medvedkudajlabku.sk – pump tracks de Bratislava", "url": "https://medvedkudajlabku.sk/pumptrack/"}]'::jsonb),
('way-995397775', 'pump', 'Pumptrack Viničné', 48.267399, 17.308286, 'Hlavná 259, Viničné (centre du village)', null, 'public', 'Ouvert en 2021, construit par BikeIng. Pas d’éclairage.', null, null, '[{"nom": "OpenStreetMap (oma.sk)", "url": "https://poi.oma.sk/w995397775"}, {"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/pump-track-vini-ne/"}, {"nom": "biker.sk – pump tracks de l’ouest", "url": "https://www.biker.sk/109062/kde-na-zapadnom-slovensku-si-mozete-zajazdit-na-pumptracku-1/"}]'::jsonb),
('dbs-sk-panssula-bahon', 'pump', 'Panšula Park Báhoň', 48.31154, 17.439325, 'Báhoň', null, null, 'En enrobé : ligne principale d’environ 100 m et ligne de sauts de 70 m. Ouvert en 2019.', null, null, '[{"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/pansula-park-baho/"}, {"nom": "biker.sk – pump tracks de l’ouest", "url": "https://www.biker.sk/109062/kde-na-zapadnom-slovensku-si-mozete-zajazdit-na-pumptracku-1/"}]'::jsonb),
('dbs-sk-lozorno', 'pump', 'Bike & scooter zóna Lozorno', 48.334909, 17.037682, 'Lozorno', null, null, '100 m en enrobé et un mini skatepark. Ouvert en 2022.', null, null, '[{"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/bike-and-scooter-zona-lozorno/"}, {"nom": "biker.sk – pump tracks de l’ouest", "url": "https://www.biker.sk/109062/kde-na-zapadnom-slovensku-si-mozete-zajazdit-na-pumptracku-1/"}]'::jsonb),
('dbs-sk-stupava', 'pump', 'Pumptrack Stupava (Kaštieľsky park)', 48.279083, 17.048262, 'Kaštieľsky park, Stupava', null, 'public', 'Petit pump track en terre pour les enfants. Pas d’éclairage.', null, null, '[{"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/pumptrack-stupava/"}, {"nom": "medvedkudajlabku.sk – pump tracks de Bratislava", "url": "https://medvedkudajlabku.sk/pumptrack/"}]'::jsonb),
('way-766778922', 'pump', 'Pumptrack Malacky', 48.438316, 17.02308, 'Na brehu 3, Malacky (près du stade)', null, null, null, null, null, '[{"nom": "OpenStreetMap (oma.sk)", "url": "https://poi.oma.sk/w766778922"}]'::jsonb),
('way-914199495', 'pump', 'Pump track d’entraînement HENKY Riders', 48.076445, 17.255793, 'Jánošíkovská 70, Dunajská Lužná', null, null, null, 'HENKY Riders', 'https://henky-riders.webnode.sk', '[{"nom": "OpenStreetMap (oma.sk)", "url": "https://poi.oma.sk/w914199495"}]'::jsonb),
('dbs-sk-trnava', 'pump', 'Pumptrack Trnava', 48.374594, 17.567054, 'Ulica Ludwiga van Beethovena, Trnava', null, 'public', 'Grand site de 6 375 m² : ligne principale d’environ 249 m, flowtrack de 198 m, boucle enfants de 87 m, pump bowl et U-ramp. Ouvert en 2023. Casque obligatoire, moins de 12 ans avec un adulte.', null, null, '[{"nom": "Ville de Trnava", "url": "https://www.trnava.sk/aktualita/12739/narocnejsia-draha-velkeho-pumptracku-je-od-dnes-otvorena-pre-skusenejsich-jazdcov"}, {"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/pump-track-trnava/"}]'::jsonb),
('dbs-sk-lovcice', 'pump', 'BikePark Lovčice', 48.36789, 17.668662, 'Dolné Lovčice', null, null, 'Terre compactée : petite piste de BMX de 257 m, pump track à 4 boucles et 3 dirts. Ouvert en 2012.', null, null, '[{"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/bikepark-lov-ice/"}, {"nom": "biker.sk – pump tracks de l’ouest", "url": "https://www.biker.sk/109062/kde-na-zapadnom-slovensku-si-mozete-zajazdit-na-pumptracku-1/"}]'::jsonb),
('dbs-sk-dlha', 'pump', 'Pumptrack Motokáry Dlhá', 48.419098, 17.415847, 'Site de karting, Dlhá', null, null, 'En enrobé, ouvert en 2021, sur un site de karting privé.', null, null, '[{"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/pumptrack-motokary-dlha/"}, {"nom": "biker.sk – pump tracks de l’ouest", "url": "https://www.biker.sk/109062/kde-na-zapadnom-slovensku-si-mozete-zajazdit-na-pumptracku-1/"}]'::jsonb),
('dbs-sk-dojc', 'pump', 'Pumptrack Dojč', 48.679062, 17.24975, 'Dojč', null, null, 'Terre compactée avec virages en béton. Ouvert en 2016.', null, null, '[{"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/pumptrack-doj/"}, {"nom": "biker.sk – pump tracks de l’ouest", "url": "https://www.biker.sk/109062/kde-na-zapadnom-slovensku-si-mozete-zajazdit-na-pumptracku-1/"}]'::jsonb),
('way-1315517662', 'pump', 'Pumptrack Nitra – Mlynárce', 48.316724, 18.043886, 'Mlynárce, terrain de RSÚC Nitra (bus 8, 18 et 21)', 'Mars – octobre : 7 h – 21 h
Novembre – février : 7 h – 19 h', 'public', 'En enrobé, aux normes de compétition. Ouvert le 3 mai 2025, construit par BikeIng. Éclairé, sous vidéosurveillance.', null, null, '[{"nom": "sita.sk – ouverture", "url": "https://sita.sk/v-nitre-slavnostne-otvorili-novy-pumptrackovy-areal-draha-ziskala-svojich-fanusikov-hned-v-prvy-den/"}, {"nom": "OpenStreetMap (oma.sk)", "url": "https://poi.oma.sk/w1315517662"}]'::jsonb),
('way-1342156261', 'pump', 'Pumptrack Cyklopoint Nitra-Chrenová', 48.314806, 18.104798, 'Trieda Andreja Hlinku 57, Nitra', null, null, null, null, null, '[{"nom": "OpenStreetMap (oma.sk)", "url": "https://poi.oma.sk/w1342156261"}]'::jsonb),
('node-3683556239', 'pump', 'Skillpark HidePumpa (Hidepark)', 48.315058, 18.067506, 'Vodná ulica, Nitra', null, null, 'Plusieurs pump tracks, gérés par l’association TRIPTYCH.', null, null, '[{"nom": "OpenStreetMap (oma.sk)", "url": "https://poi.oma.sk/n3683556239"}, {"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/skillpark-hidepumpa/"}]'::jsonb),
('way-999992384', 'pump', 'Pumptrack Cyklopark Veľké Zálužie', 48.303021, 17.937292, 'Cintorínska 26, Veľké Zálužie', null, null, null, null, null, '[{"nom": "OpenStreetMap (oma.sk)", "url": "https://poi.oma.sk/w999992384"}, {"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/pumptrack-ve-ke-zalu-ie/"}]'::jsonb),
('node-9198004319', 'pump', 'Pumptrack Topoľčany', 48.558847, 18.161771, 'Park športovcov, Topoľčany', null, null, 'En enrobé, ouvert en 2021 par la ville.', null, null, '[{"nom": "OpenStreetMap (oma.sk)", "url": "https://poi.oma.sk/n9198004319"}, {"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/pumptrack-topo--any/"}, {"nom": "biker.sk – pump tracks de l’ouest", "url": "https://www.biker.sk/109062/kde-na-zapadnom-slovensku-si-mozete-zajazdit-na-pumptracku-1/"}]'::jsonb),
('way-999983422', 'pump', 'Pumptrack Topoľčianky', 48.423242, 18.420876, 'Športová 17H, Topoľčianky', null, null, null, null, null, '[{"nom": "OpenStreetMap (oma.sk)", "url": "https://poi.oma.sk/w999983422"}, {"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/skillpark-topo--ianky/"}]'::jsonb),
('node-12576727355', 'pump', 'Pumptrack Trenčín – park pod Juhom', 48.874189, 18.03706, 'Pod Juhom 40, Trenčín (à côté de l’aire de jeux Žihadielko)', '1er avril – 31 octobre : 7 h – 22 h
1er novembre – 31 mars : 8 h – 19 h', 'public', 'Trois niveaux de difficulté et une butte de départ. Ouvert en 2024. Casque obligatoire.', null, null, '[{"nom": "Ville de Trenčín – pumptrack", "url": "https://trencin.sk/pre-obcanov/sport/pumptrack/"}, {"nom": "OpenStreetMap (oma.sk)", "url": "https://www.oma.sk/n12576727355?s=poi"}]'::jsonb),
('dbs-sk-trencin-zlatovce', 'pump', 'Pumptrack Trenčín-Zlatovce', 48.902184, 18.022878, 'Zlatovce, Trenčín', null, null, 'Construit par BikeIng.', null, null, '[{"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/pumptrack-zlatovce-by-bikeing/"}]'::jsonb),
('dbs-sk-trencianska-turna', 'pump', 'Pumptrack Trenčianska Turná', 48.847554, 18.008485, 'Beckovská 347, Trenčianska Turná', null, null, '110 m en enrobé, depuis 2017.', null, null, '[{"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/pumptrack-tren-ianska-turna/"}, {"nom": "biker.sk – pump tracks de l’ouest", "url": "https://www.biker.sk/109062/kde-na-zapadnom-slovensku-si-mozete-zajazdit-na-pumptracku-1/"}]'::jsonb),
('dbs-sk-drietoma', 'pump', 'Pumptrack Drietoma', 48.890657, 17.954766, 'Drietoma', null, null, 'En enrobé, ouvert en 2022.', null, null, '[{"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/pumptrack-drietoma/"}, {"nom": "biker.sk – pump tracks de l’ouest", "url": "https://www.biker.sk/109062/kde-na-zapadnom-slovensku-si-mozete-zajazdit-na-pumptracku-1/"}]'::jsonb),
('dbs-sk-kalnica', 'pump', 'Pumptrack Kellys Bikepark Kálnica', 48.754109, 17.937732, 'Kellys Bikepark, Kálnica', null, null, 'En enrobé, ouvert en 2016 par BikeIng. Accueille le BikeFest chaque année.', null, null, '[{"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/pumptrack-kellys-bikepark-kalnica/"}, {"nom": "biker.sk – pump tracks de l’ouest", "url": "https://www.biker.sk/109062/kde-na-zapadnom-slovensku-si-mozete-zajazdit-na-pumptracku-1/"}]'::jsonb),
('dbs-sk-ivanovce', 'pump', 'Pumptrack Ivanovce', 48.827995, 17.910205, 'Ivanovce', null, null, 'En enrobé, ouvert en 2020.', null, null, '[{"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/pumptrack-ivanovce/"}, {"nom": "biker.sk – pump tracks de l’ouest", "url": "https://www.biker.sk/109062/kde-na-zapadnom-slovensku-si-mozete-zajazdit-na-pumptracku-1/"}]'::jsonb),
('way-1071062523', 'pump', 'Pumptrack Selec', 48.793121, 17.98528, 'Selec', null, null, null, null, null, '[{"nom": "OpenStreetMap (oma.sk)", "url": "https://poi.oma.sk/w1071062523"}, {"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/pumptrack-selec/"}]'::jsonb),
('dbs-sk-beckov', 'pump', 'Pumptrack Beckov', 48.793303, 17.89813, 'Beckov', null, null, 'Construit par BikeIng.', null, null, '[{"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/pumptrack-beckov-by-bikeing/"}]'::jsonb),
('dbs-sk-bohuslavice', 'pump', 'Pumptrack Bohuslavice', 48.79921, 17.858029, 'Bohuslavice', null, null, null, null, null, '[{"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/pumptrack-bohuslavice/"}]'::jsonb),
('dbs-sk-bosaca', 'pump', 'Pumptrack Bošáca', 48.828367, 17.834411, 'Bošáca', null, null, 'Terre compactée avec virages en enrobé. Ouvert en 2017.', null, null, '[{"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/pumptrack-bosaca/"}, {"nom": "biker.sk – pump tracks de l’ouest", "url": "https://www.biker.sk/109062/kde-na-zapadnom-slovensku-si-mozete-zajazdit-na-pumptracku-1/"}]'::jsonb),
('dbs-sk-hradok', 'pump', 'Pumptrack MTBiker Hrádok', 48.696122, 17.883282, 'Hrádok', null, null, 'En enrobé, ouvert en 2018.', null, null, '[{"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/pumptrack-mtbiker-hradok-5051/"}, {"nom": "biker.sk – pump tracks de l’ouest", "url": "https://www.biker.sk/109062/kde-na-zapadnom-slovensku-si-mozete-zajazdit-na-pumptracku-1/"}]'::jsonb),
('dbs-sk-myjava-dema', 'pump', 'DEMA minibikepark Myjava', 48.756613, 17.571446, 'Myjava', null, null, 'Piste BMX / VTT, dirts et pump track pour les enfants.', null, null, '[{"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/dema-minibikepark-myjava/"}]'::jsonb),
('way-1049422636', 'pump', 'Pumptrack Beluša', 49.048595, 18.305682, 'Beluša', null, 'public', 'En enrobé, ouvert en 2022. Abri, barbecue et parking.', null, null, '[{"nom": "OpenStreetMap (oma.sk)", "url": "https://poi.oma.sk/w1049422636"}, {"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/pumptrack-belusa/"}, {"nom": "biker.sk – pump tracks de l’ouest", "url": "https://www.biker.sk/109062/kde-na-zapadnom-slovensku-si-mozete-zajazdit-na-pumptracku-1/"}]'::jsonb),
('dbs-sk-dohnany', 'pump', 'Pumptrack Dohňany', 49.155369, 18.27943, 'Dohňany', null, null, 'Construit par BikeIng.', null, null, '[{"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/pumptrack-dohnany-by-bikeing/"}]'::jsonb),
('dbs-sk-partizanske', 'pump', 'Pumptrack Partizánske', 48.620182, 18.340763, 'Parc municipal, Malé Bielice, Partizánske', null, null, 'En enrobé : boucle extérieure de 100 à 130 m (4 virages, 12 bosses) et ligne intérieure de 33 m. Ouvert en 2021, construit par BikeIng.', null, null, '[{"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/pumptrack-7160/"}, {"nom": "biker.sk – pump tracks de l’ouest", "url": "https://www.biker.sk/109062/kde-na-zapadnom-slovensku-si-mozete-zajazdit-na-pumptracku-1/"}]'::jsonb),
('dbs-sk-novaky', 'pump', 'Pumptrack Nováky', 48.717056, 18.542414, 'Rastislavova, Nováky', null, null, 'En enrobé (rénové).', null, null, '[{"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/pumptrack-novaky/"}]'::jsonb),
('dbs-sk-zilina-kia', 'pump', 'KIA Pumptrack Žilina (Vodné dielo)', 49.212264, 18.779127, 'Cesta na Mojš 1375, bike park du barrage, Žilina', null, 'public', '180 m en enrobé. Ouvert le 15 juin 2018 (Fondation Kia Slovakia, la ville et Pumptrack Slovakia).', null, null, '[{"nom": "teraz.sk – ouverture", "url": "https://www.teraz.sk/regiony/zilina-v-bike-parku-na-vodnom-diele-ot/331406-clanok.html"}, {"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/pumptrack--ilina/"}]'::jsonb),
('way-1521455308', 'pump', 'Pumptrack Varín', 49.195376, 18.867684, 'Priemyselná, derrière le pont du chemin de fer, Varín', null, 'public', 'Deux boucles en enrobé. Ouvert au printemps 2026.', null, null, '[{"nom": "zilinskyvecernik.sk – ouverture", "url": "https://www.zilinskyvecernik.sk/clanok/vo-varine-otvorili-pumptrackovu-drahu-blizko-noveho-cyklochodnika/16788/"}, {"nom": "OpenStreetMap (oma.sk)", "url": "https://poi.oma.sk/w1521455308"}]'::jsonb),
('way-1023290794', 'pump', 'Pumptrack Horný Hričov', 49.259189, 18.662608, 'Horný Hričov', null, 'public', 'Construit par BikeIng.', null, null, '[{"nom": "OpenStreetMap (oma.sk)", "url": "https://poi.oma.sk/w1023290794"}]'::jsonb),
('way-684547321', 'pump', 'Pumptrack pod Hríbom (Raková)', 49.446983, 18.745066, 'Chata pod Hríbom, Raková', null, null, 'Petit pump track en triangle (environ 20 m).', null, null, '[{"nom": "OpenStreetMap (oma.sk)", "url": "https://poi.oma.sk/w684547321"}]'::jsonb),
('way-767855502', 'pump', 'KIA Pumptrack Martin – Pltníky', 49.089309, 18.923418, 'Šport park Pltníky, Pltníky 25, Martin', 'Horaires du parc : lundi – vendredi 10 h – 21 h, samedi – dimanche 8 h – 20 h', null, 'En enrobé, construit par Pumptrack.sk avec la Fondation Kia.', null, null, '[{"nom": "OpenStreetMap (oma.sk)", "url": "https://poi.oma.sk/w767855502"}, {"nom": "Trailforks", "url": "https://www.trailforks.com/skillpark/pumptrack-martin/"}]'::jsonb),
('dbs-sk-zabokreky', 'pump', 'Pumptrack Žabokreky', 49.021713, 18.924856, 'Žabokreky', null, null, null, null, null, '[{"nom": "Trailforks – skillparks de Slovaquie", "url": "https://www.trailforks.com/region/slovakia/skillparks/"}]'::jsonb),
('way-1076541614', 'pump', 'Pumptrack Oravská Polhora', 49.524009, 19.43937, 'Športová 3, Oravská Polhora', null, null, 'Deux pistes en enrobé : 400 m et 100 m. Ouvert en 2018.', null, null, '[{"nom": "OpenStreetMap (oma.sk)", "url": "https://poi.oma.sk/w1076541614"}]'::jsonb),
('way-996278667', 'pump', 'Pumptrack Zákamenné', 49.382497, 19.283462, 'Športová 11, Zákamenné', null, null, null, null, null, '[{"nom": "OpenStreetMap (oma.sk)", "url": "https://poi.oma.sk/w996278667"}]'::jsonb),
('way-914206731', 'pump', 'Pumptrack & BMX park Liptovský Mikuláš', 49.0714094, 19.6270417, 'Vrbica, Liptovský Mikuláš (à côté de la piste de BMX)', null, 'public', '280 m en enrobé, 3 boucles. Ouvert le 25 août 2023, construit par BikeIng. Le plus grand site de pump track du nord de la Slovaquie.', null, null, '[{"nom": "visitliptov – Pumptrack & BMX park", "url": "https://www.visitliptov.sk/en/interests/pumptrack-bmx-park/"}, {"nom": "teraz.sk – ouverture", "url": "https://www.teraz.sk/regiony/liptovsky-mikulas-otvoril-najvacs/736798-clanok.html"}, {"nom": "OpenStreetMap (oma.sk)", "url": "https://poi.oma.sk/w914206731"}]'::jsonb),
('way-995402549', 'pump', 'Pumptrack Laskomer', 48.747877, 19.11667, 'Laskomerská dolina, Podlavice, Banská Bystrica', null, 'public', 'Virages en enrobé et lignes droites en gravier, avec une ligne de dirt. Ouvert le 30 juin 2018 par l’association KoLesom (bénévoles).', 'OZ KoLesom', null, '[{"nom": "mtbiker.sk – ouverture", "url": "https://www.mtbiker.sk/clanky/10242/pozvanka-novy-pumptrack-v-laskomerskej-doline-oficialne-otvorenie-uz-tuto-sobotu.html"}, {"nom": "OpenStreetMap (oma.sk)", "url": "https://poi.oma.sk/w995402549"}]'::jsonb),
('way-1424339264', 'pump', 'Pumptrack Bike Park Mýto pod Ďumbierom', 48.844876, 19.619587, 'Mýto pod Ďumbierom', null, null, null, null, null, '[{"nom": "OpenStreetMap (oma.sk)", "url": "https://poi.oma.sk/w1424339264"}]'::jsonb),
('way-996122338', 'pump', 'Pumptrack Hriňová', 48.572149, 19.525834, 'Lúčna 3A, Hriňová (à côté de la piscine d’été)', null, null, '120 m en enrobé, 2 m de large. Ouvert en 2021.', null, null, '[{"nom": "OpenStreetMap (oma.sk)", "url": "https://poi.oma.sk/w996122338"}]'::jsonb),
('node-9231212327', 'pump', 'Pumptrack Detva', 48.5479637, 19.4094833, 'Dolinky 20, Detva (près du stade de foot)', null, null, null, null, null, '[{"nom": "OpenStreetMap (oma.sk)", "url": "https://poi.oma.sk/n9231212327"}]'::jsonb),
('dbs-sk-ziar', 'pump', 'Pumptrack Žiar nad Hronom', 48.585386, 18.855561, 'Hviezdoslavova 275/19, Žiar nad Hronom', null, null, null, null, null, '[{"nom": "Trailforks – skillparks de Slovaquie", "url": "https://www.trailforks.com/region/slovakia/skillparks/"}]'::jsonb),
('node-10826792900', 'pump', 'Pumptrack Bikepark Žarnovica', 48.4892636, 18.6944668, 'Žarnovická Huta, Žarnovica', null, null, null, null, null, '[{"nom": "OpenStreetMap (oma.sk)", "url": "https://poi.oma.sk/n10826792900"}]'::jsonb),
('way-1155995822', 'pump', 'PUMP track & DIRT park Prešov (Bike Centrum)', 48.990738, 21.260524, 'Rusínska 5, Prešov', null, null, 'Trois boucles en enrobé (petits, enfants, confirmés). Sur le terrain d’un magasin de vélos avec café.', null, null, '[{"nom": "OpenStreetMap (oma.sk)", "url": "https://poi.oma.sk/w1155995822"}]'::jsonb),
('way-1171763071', 'pump', 'Pumptrack Veľký Šariš', 49.034978, 21.201929, 'Doliny, au bord de la Torysa, Veľký Šariš', null, null, '350 m² en enrobé et un skatepark. Ouvert en 2021.', null, null, '[{"nom": "presovregion.travel", "url": "https://presovregion.travel/clanok/novy-pumptrack-vo-velkom-sarisi/"}, {"nom": "OpenStreetMap (oma.sk)", "url": "https://poi.oma.sk/w1171763071"}]'::jsonb),
('way-981552978', 'pump', 'Pumptrack Humenné', 48.93771, 21.913626, 'Osloboditeľov 16, Humenné', null, 'public', '106 m en enrobé. Ouvert en septembre 2021. Éclairé, clôturé, avec parking et fontaine.', null, null, '[{"nom": "kosiceonline.sk – ouverture", "url": "https://www.kosiceonline.sk/v-humennom-otvorili-treti-pumptrack-na-vychode-slovenska"}, {"nom": "OpenStreetMap (oma.sk)", "url": "https://poi.oma.sk/w981552978"}]'::jsonb),
('way-1186016264', 'pump', 'Pumptrack Kežmarok (Zlatná)', 49.160294, 20.44783, 'Zone de loisirs Zlatná, près de la piste cyclable, Kežmarok', null, 'public', 'Ouvert fin 2017 avec des fonds européens.', null, null, '[{"nom": "OpenStreetMap (oma.sk)", "url": "https://poi.oma.sk/w1186016264"}]'::jsonb),
('dbs-sk-spisska-bela', 'pump', 'Pumptrack Spišská Belá', 49.195859, 20.438034, 'Bike park du Beliansky rybník, Spišská Belá', 'Tous les jours, sans limite d’horaire', 'public', '183 m en enrobé. Ouvert en 2018, construit par BikeIng.', null, null, '[{"nom": "Ville de Spišská Belá", "url": "https://spisskabela.sk/mesto/aktuality/pumptrack-v-novom-bike-parku-pri-belianskom-rybniku-sa-uz-uziva/"}, {"nom": "domalenka.sk", "url": "https://domalenka.sk/atrakcie/pumptrack-spisska-bela"}]'::jsonb),
('dbs-sk-velka-lomnica', 'pump', 'Bike Park Veľká Lomnica', 49.111295, 20.36425, 'Près de la route I/66 et de la piste cyclable, Veľká Lomnica', null, 'public', 'Pump track en enrobé et bowl en béton. Ouvert au printemps 2024.', null, null, '[{"nom": "kosiceonline.sk – nouveau bike park", "url": "https://www.kosiceonline.sk/vo-velkej-lomnici-vznikol-novy-bikepark"}]'::jsonb),
('way-1250723582', 'pump', 'KSK Pumptrack Košice', 48.700697, 21.242359, 'Moldavská cesta 22, derrière le parking du Hornbach, Košice', null, 'public', '129 m par tour en enrobé. Seul pump track homologué UCI en Slovaquie : il accueille une qualification pour les championnats du monde de pump track. Ouvert en juin 2024, construit par Velosolutions.', null, null, '[{"nom": "teraz.sk – pump track homologué UCI", "url": "https://www.teraz.sk/regiony/v-kosiciach-otvorili-pumptrack-s-certif/802673-clanok.html"}, {"nom": "OpenStreetMap (oma.sk)", "url": "https://poi.oma.sk/w1250723582"}]'::jsonb),
('node-8514585498', 'pump', 'Pumptrack Drábova (Dirtpark KVP)', 48.7059881, 21.2171851, 'Drábova, Košice (KVP)', null, null, 'En enrobé, avec des dirts. Ouvert le 23 avril 2022 (budget participatif).', 'OZ Enjoy the Ride', null, '[{"nom": "kosicednes.sk – ouverture", "url": "https://kosicednes.sk/spravy/pumptrack-na-sidlisku-kvp-dnes-caka-oficialne-otvorenie-foto/"}, {"nom": "OpenStreetMap (oma.sk)", "url": "https://poi.oma.sk/n8514585498"}]'::jsonb),
('way-1410991600', 'pump', 'Pumptrack Parchovany', 48.747071, 21.713618, 'Hlavná 21, parc, Parchovany', null, null, 'Ouvert en juin 2024.', null, null, '[{"nom": "OpenStreetMap (oma.sk)", "url": "https://poi.oma.sk/w1410991600"}]'::jsonb)
on conflict (id) do update set genre = excluded.genre, nom = excluded.nom, latitude = excluded.latitude, longitude = excluded.longitude, adresse = excluded.adresse, horaires = excluded.horaires, acces = excluded.acces, trace = excluded.trace, club = excluded.club, club_site = excluded.club_site, sources = excluded.sources;


-- Compétition à venir sur la piste de Dunajská Lužná
insert into public.competitions (lieu_id, nom, date_debut, date_fin, niveau, lien)
values ('way-78169544', 'Coupe de Slovaquie de BMX Racing – manches 8 et 9', '2026-10-03', '2026-10-04', 'National (Slovenský pohár)', 'https://www.kosickysarkan.sk/sezona');
